<?php
$currentCat = Mage::registry('current_category');

$_categoryChildren =  Mage::getModel('catalog/category')->load($currentCat->getId())->getChildren();

var_dump($_categoryChildren);

if ($_categoryChildren) {
    
}

/*if ( $currentCat->getParentId() == Mage::app()->getStore()->getRootCategoryId() ) {
    // current category is a toplevel category
    $loadCategory = $currentCat;
} else {
    // current category is a sub-(or subsub-, etc...)category of a toplevel category
    // load the parent category of the current category
    $loadCategory = Mage::getModel('catalog/category')->load($currentCat->getParentId());
}*/
$subCategories = explode(',', $loadCategory->getChildren());
var_dump($subCategories);
?>
<?php if($subCategories): ?>
    <div class="nav-sidebar">
        <ul class="category-list">
    <?php foreach ( $subCategories as $subCategoryId ): ?>
        <?php $cat = Mage::getModel('catalog/category')->load($subCategoryId); ?>
        <?php if($cat->getIsActive()): ?>
            <?php //echo '<a href="'.$cat->getURL().'">'.$cat->getName().'</a>'; ?>
            <li<?php if($cat->getId()==$currentCat->getId()) echo ' class="current"' ?>><a href="<?php echo $cat->getURL() ?>"><?php echo $cat->getName() ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
        </ul>
    </div>
<?php else: ?>
    <?php
    $obj = new Mage_Catalog_Block_Navigation();
    $store_cats	= $obj->getStoreCategories();
    $current_cat 	= $obj->getCurrentCategory();
    //$current_cat	= (is_object($current_cat) ? $current_cat->getName() : '');

    //get the children of the current category
    $subCats = Mage::getModel('catalog/category')->load($current_cat->getId())->getChildren();

    //get sub category ids
    $subCatIds = explode(',',$subCats);

    ?>
    <?php if ($store_cats): ?>
        <div class="nav-sidebar">
            <ul class="category-list">
                <?php
                foreach ($store_cats as $cat) {
                    if ($cat->getId() == $current_cat->getId()) {
                        echo '<li class="current"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a>\n<ul>\n";
                        foreach ($obj->getCurrentChildCategories() as $subcat) {
                            echo '<li><a href="'.$this->getCategoryUrl($subcat).'">'.$subcat->getName()."</a></li>\n";
                        }
                        echo "</ul>\n</li>\n";
                    } else {
                        echo '<li><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a></li>\n";
                    }
                }
                ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>