<div class="mini-cart-layer">
    <?php if ($this->getIsNeedToDisplaySideBar()):?>
        <div class="top-cart">
            <?php $_cartQty = $this->getSummaryCount() ?>
            <?php if ($_cartQty > 0): ?>
                <?php $_myCart = $this->__('Shopping Cart (%s items)', $_cartQty) ?>
            <?php else: ?>
                <?php $_myCart = $this->__('Shopping Cart (0 item)') ?>
            <?php endif ?>

            <?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()):?>
                <div class="block-title no-items">
                    <ul class="links cart-link">
                        <li><a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $_myCart ?></a></li>
                    </ul>
                </div>
            <?php else:?>
                <div class="block-title<?php if(!$_cartQty) { echo (' no-items'); } ?>">
                    <span id="cartHeader"><?php echo $_myCart ?></span>
                </div>
                <div id="topCartContent" class="block-content" style="display:none">
                    <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
                        <?php $_items = $this->getRecentItems() ?>
                        <?php if(count($_items)): ?>
                            <p class="block-subtitle">
                                <span onclick="toggleTopCart();" class="close-btn"><?php echo $this->__('Close'); ?></span>
                                <?php echo $this->__('Recently added item(s)') ?>
                            </p>
                            <ol id="mini-cart" class="mini-products-list">
                                <?php foreach($_items as $_item): ?>
                                    <?php echo $this->getItemHtml($_item) ?>
                                <?php endforeach; ?>
                            </ol>
                            <script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
                        <?php else: ?>
                            <p class="block-subtitle">
                                <span onclick="toggleTopCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
                                <?php echo $this->__('Recently added item(s)') ?>
                            </p>
                            <p class="cart-empty">
                                <?php echo $this->__('You have no items in your shopping cart.') ?>
                            </p>
                        <?php endif ?>
                        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                            <div class="actions">
                                <a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $this->__('Go to Shopping Cart') ?></a>
                                <button class="button" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            <?php endif;?>
        </div>
    <?php endif;?>
</div>